# Generated by Django 5.1.7 on 2025-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dish_ingredients", to="kitchen_app.ingredient"
            ),
        ),
    ]
