# Generated by Django 5.1.7 on 2025-03-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_app", "0002_ingredient_dishmodel_ingredients"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DishType",
            new_name="DishTypeModel",
        ),
        migrations.RenameModel(
            old_name="Ingredient",
            new_name="IngredientModel",
        ),
        migrations.AlterModelOptions(
            name="cookmodel",
            options={"ordering": ["username"]},
        ),
    ]
