# Generated by Django 5.1.7 on 2025-03-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_app", "0003_rename_dishtype_dishtypemodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishmodel",
            options={"ordering": ["price"]},
        ),
    ]
