# Generated by Django 5.1.7 on 2025-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0004_alter_dishmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtypemodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredientmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='dishmodel',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dishmodel',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='dishmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
